apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: jwt-inspect
  labels:
    app: jwt-inspect
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jwt-inspect
      version: v1
  template:
    metadata:
      labels:
        app: jwt-inspect
        version: v1
    spec:
      containers:
      - image: ghcr.io/openmicrotools/jwt-inspect:latest
        imagePullPolicy: IfNotPresent
        name: jwt-inspect
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 16Mi
            cpu: 20m
          requests:
            memory: 4Mi
            cpu: 10m
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 3

# # Uncomment block to add custom css 
#         volumeMounts:
#         - name: customize-css
#           mountPath: assets/css/customize.css
#           subPath: assets/css/customize.css 
#       volumes:
#         - name: customize-css
#           configMap: 
#             name: customize-css
#             items:
#               - key: customize.css  
#                 path: assets/css/customize.css 
