apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: jwt-inspect
  labels:
    app: jwt-inspect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwt-inspect
      version: v1
  template:
    metadata:
      labels:
        app: jwt-inspect
        version: v1
    spec:
      containers:
      - image: ghcr.io/openmicrotools/jwt-inspect:latest
        imagePullPolicy: IfNotPresent
        name: jwt-inspect
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 16Mi
            cpu: 20m
          requests:
            memory: 4Mi
            cpu: 10m


# Comment out to remove custom css 
        volumeMounts:
        - name: customize-css
          mountPath: assets/css/customize.css # This should be your final destination
          subPath: assets/css/customize.css # The name of the file to be placed inside /etc, the filename used here and in mountPath should be same.
      volumes:
        - name: customize-css
          configMap: 
            name: customize-css
            items:
              - key: customize.css  # Name of the item we had used inside our ConfigMap (under data:)
                path: assets/css/customize.css # Name of the file to be placed inside /etc

