resources:
  - deployment.yaml
  - service.yaml
  - namespace.yaml
  - ../css

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/openmicrotools/jwt-inspect
  newTag: latest

metadata:
  annotations:
    name: jwt-inspect
  labels:
    app: jwt-inspect
namespace: open-microtools

## Uncomment block to load files to the deployment via configmap
## Will also need to uncomment related files.
# configMapGenerator:
# generatorOptions:
#  disableNameSuffixHash: true

## Uncomment for custom styles for pages
# - name: customize-css
#   files:
#   - assets/customize.css
## Add configmap here for a content customized index.html page
