resources:
  - deployment.yaml
  - service.yaml
  - namespace.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Comment out block to not load css to the deployment via configmap

configMapGenerator:


  - name: customize-css
    files:
    - customize.css
generatorOptions:
    disableNameSuffixHash: true