apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: jwt-inspect
  name: jwt-inspect
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: jwt-inspect

