apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- ../../base

images:
- name: ghcr.io/openmicrotools/jwt-inspect
  newTag: latest

metadata:
  annotations:
    name: jwt-inspect
  labels:
    app: jwt-inspect
namespace: open-microtools

patchesStrategicMerge:
  - service-patch.yaml
