apiVersion: v1
kind: Namespace
metadata:
  name: open-microtools
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jwt-inspect
  name: jwt-inspect
  namespace: open-microtools
spec:
  ports:
  - name: webport
    nodePort: 30443
    port: 80
    targetPort: 8080
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: jwt-inspect
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jwt-inspect
    version: v1
  name: jwt-inspect
  namespace: open-microtools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwt-inspect
      version: v1
  template:
    metadata:
      labels:
        app: jwt-inspect
        version: v1
    spec:
      containers:
      - image: ghcr.io/openmicrotools/jwt-inspect:latest
        imagePullPolicy: IfNotPresent
        name: jwt-inspect
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 20m
            memory: 16Mi
          requests:
            cpu: 10m
            memory: 4Mi
