apiVersion: v1 
kind: Service
metadata:
  name: jwt-inspect
  labels:
    app: jwt-inspect
spec:
  type: NodePort
  ports:
  - name: webport
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30443
  selector:
    app: jwt-inspect
